package com.cn.zbin.wechat.mapper;

import com.cn.zbin.wechat.dto.WeChatMessageHistory;
import com.cn.zbin.wechat.dto.WeChatMessageHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeChatMessageHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int countByExample(WeChatMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int deleteByExample(WeChatMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int insert(WeChatMessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int insertSelective(WeChatMessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    List<WeChatMessageHistory> selectByExample(WeChatMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WeChatMessageHistory record, @Param("example") WeChatMessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatmessagehistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WeChatMessageHistory record, @Param("example") WeChatMessageHistoryExample example);
    
    
    List<WeChatMessageHistory> selectOnePageByExample(@Param("example") WeChatMessageHistoryExample example,
    		@Param("offset") Integer offset, @Param("limit") Integer limit, 
    		@Param("orderByClause") String orderByClause);
}