eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 80
spring:
  application:
    name: service-ribbon
qlh:
  imagesPath: file:/C:/qlh/image/
hystrix:   
  threadpool:   
    default:   
      coreSize: 500  #并发执行的最大线程数，默认10  
  command:   
    paas-file:   
      execution:   
        isolation:   
          thread:   
            timeoutInMilliseconds: 3600000   
    default:   
      execution:   
        isolation:   
          thread:   
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms  