eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 80
spring:
#  profiles:
#    #指定读取配置文件:dev(开发环境),prod(生产环境)
#    active: prod
  application:
    name: service-ribbon
qlh:
#  imagesPath: file:/C:/qlh/image/
  imagesPath: file:/data/qlh/image/
hystrix:   
  threadpool:   
    default:   
      coreSize: 500  #并发执行的最大线程数，默认10  
  command:   
    paas-file:   
      execution:   
        isolation:   
          thread:   
            timeoutInMilliseconds: 3600000   
    default:   
      execution:   
        isolation:   
          thread:   
            timeoutInMilliseconds: 8000  #命令执行超时时间，默认1000ms

#日志相关配置
logging:
  config: classpath:logback-${spring.profiles.active}.xml