package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.MasterCity;
import com.cn.zbin.store.dto.MasterCityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MasterCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int countByExample(MasterCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int deleteByExample(MasterCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int insert(MasterCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int insertSelective(MasterCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    List<MasterCity> selectByExample(MasterCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    MasterCity selectByPrimaryKey(String cityCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MasterCity record, @Param("example") MasterCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MasterCity record, @Param("example") MasterCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MasterCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mastercity
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MasterCity record);
}