package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.MessageHistory;
import com.cn.zbin.store.dto.MessageHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int countByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int deleteByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int insert(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int insertSelective(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    List<MessageHistory> selectByExample(MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    MessageHistory selectByPrimaryKey(String messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MessageHistory record, @Param("example") MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MessageHistory record, @Param("example") MessageHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MessageHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table messagehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MessageHistory record);
}