package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.OrderProduct;
import com.cn.zbin.store.dto.OrderProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int countByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int deleteByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String orderProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int insert(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int insertSelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    List<OrderProduct> selectByExample(OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    OrderProduct selectByPrimaryKey(String orderProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") OrderProduct record, @Param("example") OrderProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderproduct
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrderProduct record);
    
    
    
    int countOrderByLeaseFlag(@Param("lease") Integer lease);
}