package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.ProductServiceArea;
import com.cn.zbin.store.dto.ProductServiceAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductServiceAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int countByExample(ProductServiceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int deleteByExample(ProductServiceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String productServiceAreaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int insert(ProductServiceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int insertSelective(ProductServiceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    List<ProductServiceArea> selectByExample(ProductServiceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    ProductServiceArea selectByPrimaryKey(String productServiceAreaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ProductServiceArea record, @Param("example") ProductServiceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ProductServiceArea record, @Param("example") ProductServiceAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductServiceArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productservicearea
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductServiceArea record);
}