package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.ShoppingTrolleyInfo;
import com.cn.zbin.store.dto.ShoppingTrolleyInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShoppingTrolleyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int countByExample(ShoppingTrolleyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int deleteByExample(ShoppingTrolleyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String trolleyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int insert(ShoppingTrolleyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingTrolleyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    List<ShoppingTrolleyInfo> selectByExample(ShoppingTrolleyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    ShoppingTrolleyInfo selectByPrimaryKey(String trolleyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ShoppingTrolleyInfo record, @Param("example") ShoppingTrolleyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ShoppingTrolleyInfo record, @Param("example") ShoppingTrolleyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingTrolleyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shoppingtrolley
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingTrolleyInfo record);
}