package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.WeChatUserInfo;
import com.cn.zbin.store.dto.WeChatUserInfoExample;
import java.util.List;

public interface WeChatUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int countByExample(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int insert(WeChatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int insertSelective(WeChatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    List<WeChatUserInfo> selectByExample(WeChatUserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    WeChatUserInfo selectByPrimaryKey(String openId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WeChatUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatuser
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WeChatUserInfo record);
}