package com.cn.zbin.store.mapper;

import com.cn.zbin.store.dto.WxRefundHistory;
import com.cn.zbin.store.dto.WxRefundHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxRefundHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int countByExample(WxRefundHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int deleteByExample(WxRefundHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String outRefundNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int insert(WxRefundHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int insertSelective(WxRefundHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    List<WxRefundHistory> selectByExample(WxRefundHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    WxRefundHistory selectByPrimaryKey(String outRefundNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") WxRefundHistory record, @Param("example") WxRefundHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") WxRefundHistory record, @Param("example") WxRefundHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(WxRefundHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wxrefundhistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(WxRefundHistory record);
}