package com.cn.zbin.store.dto;

public class CustomerAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.cust_address_id
     *
     * @mbggenerated
     */
    private String custAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.seq_no
     *
     * @mbggenerated
     */
    private Integer seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.province_code
     *
     * @mbggenerated
     */
    private String provinceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.city_code
     *
     * @mbggenerated
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.recipient_address
     *
     * @mbggenerated
     */
    private String recipientAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.recipient_name
     *
     * @mbggenerated
     */
    private String recipientName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.recipient_phone
     *
     * @mbggenerated
     */
    private String recipientPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.default_flag
     *
     * @mbggenerated
     */
    private Boolean defaultFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customeraddress.delete_flag
     *
     * @mbggenerated
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.cust_address_id
     *
     * @return the value of customeraddress.cust_address_id
     *
     * @mbggenerated
     */
    public String getCustAddressId() {
        return custAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.cust_address_id
     *
     * @param custAddressId the value for customeraddress.cust_address_id
     *
     * @mbggenerated
     */
    public void setCustAddressId(String custAddressId) {
        this.custAddressId = custAddressId == null ? null : custAddressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.seq_no
     *
     * @return the value of customeraddress.seq_no
     *
     * @mbggenerated
     */
    public Integer getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.seq_no
     *
     * @param seqNo the value for customeraddress.seq_no
     *
     * @mbggenerated
     */
    public void setSeqNo(Integer seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.customer_id
     *
     * @return the value of customeraddress.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.customer_id
     *
     * @param customerId the value for customeraddress.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.province_code
     *
     * @return the value of customeraddress.province_code
     *
     * @mbggenerated
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.province_code
     *
     * @param provinceCode the value for customeraddress.province_code
     *
     * @mbggenerated
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.city_code
     *
     * @return the value of customeraddress.city_code
     *
     * @mbggenerated
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.city_code
     *
     * @param cityCode the value for customeraddress.city_code
     *
     * @mbggenerated
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.recipient_address
     *
     * @return the value of customeraddress.recipient_address
     *
     * @mbggenerated
     */
    public String getRecipientAddress() {
        return recipientAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.recipient_address
     *
     * @param recipientAddress the value for customeraddress.recipient_address
     *
     * @mbggenerated
     */
    public void setRecipientAddress(String recipientAddress) {
        this.recipientAddress = recipientAddress == null ? null : recipientAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.recipient_name
     *
     * @return the value of customeraddress.recipient_name
     *
     * @mbggenerated
     */
    public String getRecipientName() {
        return recipientName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.recipient_name
     *
     * @param recipientName the value for customeraddress.recipient_name
     *
     * @mbggenerated
     */
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName == null ? null : recipientName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.recipient_phone
     *
     * @return the value of customeraddress.recipient_phone
     *
     * @mbggenerated
     */
    public String getRecipientPhone() {
        return recipientPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.recipient_phone
     *
     * @param recipientPhone the value for customeraddress.recipient_phone
     *
     * @mbggenerated
     */
    public void setRecipientPhone(String recipientPhone) {
        this.recipientPhone = recipientPhone == null ? null : recipientPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.default_flag
     *
     * @return the value of customeraddress.default_flag
     *
     * @mbggenerated
     */
    public Boolean getDefaultFlag() {
        return defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.default_flag
     *
     * @param defaultFlag the value for customeraddress.default_flag
     *
     * @mbggenerated
     */
    public void setDefaultFlag(Boolean defaultFlag) {
        this.defaultFlag = defaultFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customeraddress.delete_flag
     *
     * @return the value of customeraddress.delete_flag
     *
     * @mbggenerated
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customeraddress.delete_flag
     *
     * @param deleteFlag the value for customeraddress.delete_flag
     *
     * @mbggenerated
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}