package com.cn.zbin.store.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderOperationHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public OrderOperationHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderOperIdIsNull() {
            addCriterion("order_oper_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdIsNotNull() {
            addCriterion("order_oper_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdEqualTo(String value) {
            addCriterion("order_oper_id =", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotEqualTo(String value) {
            addCriterion("order_oper_id <>", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdGreaterThan(String value) {
            addCriterion("order_oper_id >", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_oper_id >=", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLessThan(String value) {
            addCriterion("order_oper_id <", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLessThanOrEqualTo(String value) {
            addCriterion("order_oper_id <=", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLike(String value) {
            addCriterion("order_oper_id like", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotLike(String value) {
            addCriterion("order_oper_id not like", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdIn(List<String> values) {
            addCriterion("order_oper_id in", values, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotIn(List<String> values) {
            addCriterion("order_oper_id not in", values, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdBetween(String value1, String value2) {
            addCriterion("order_oper_id between", value1, value2, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotBetween(String value1, String value2) {
            addCriterion("order_oper_id not between", value1, value2, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIsNull() {
            addCriterion("order_product_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIsNotNull() {
            addCriterion("order_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdEqualTo(String value) {
            addCriterion("order_product_id =", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotEqualTo(String value) {
            addCriterion("order_product_id <>", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdGreaterThan(String value) {
            addCriterion("order_product_id >", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_product_id >=", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLessThan(String value) {
            addCriterion("order_product_id <", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLessThanOrEqualTo(String value) {
            addCriterion("order_product_id <=", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLike(String value) {
            addCriterion("order_product_id like", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotLike(String value) {
            addCriterion("order_product_id not like", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIn(List<String> values) {
            addCriterion("order_product_id in", values, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotIn(List<String> values) {
            addCriterion("order_product_id not in", values, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdBetween(String value1, String value2) {
            addCriterion("order_product_id between", value1, value2, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotBetween(String value1, String value2) {
            addCriterion("order_product_id not between", value1, value2, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeIsNull() {
            addCriterion("ask_oper_code is null");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeIsNotNull() {
            addCriterion("ask_oper_code is not null");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeEqualTo(String value) {
            addCriterion("ask_oper_code =", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeNotEqualTo(String value) {
            addCriterion("ask_oper_code <>", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeGreaterThan(String value) {
            addCriterion("ask_oper_code >", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ask_oper_code >=", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeLessThan(String value) {
            addCriterion("ask_oper_code <", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeLessThanOrEqualTo(String value) {
            addCriterion("ask_oper_code <=", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeLike(String value) {
            addCriterion("ask_oper_code like", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeNotLike(String value) {
            addCriterion("ask_oper_code not like", value, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeIn(List<String> values) {
            addCriterion("ask_oper_code in", values, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeNotIn(List<String> values) {
            addCriterion("ask_oper_code not in", values, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeBetween(String value1, String value2) {
            addCriterion("ask_oper_code between", value1, value2, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAskOperCodeNotBetween(String value1, String value2) {
            addCriterion("ask_oper_code not between", value1, value2, "askOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeIsNull() {
            addCriterion("ans_oper_code is null");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeIsNotNull() {
            addCriterion("ans_oper_code is not null");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeEqualTo(String value) {
            addCriterion("ans_oper_code =", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeNotEqualTo(String value) {
            addCriterion("ans_oper_code <>", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeGreaterThan(String value) {
            addCriterion("ans_oper_code >", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeGreaterThanOrEqualTo(String value) {
            addCriterion("ans_oper_code >=", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeLessThan(String value) {
            addCriterion("ans_oper_code <", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeLessThanOrEqualTo(String value) {
            addCriterion("ans_oper_code <=", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeLike(String value) {
            addCriterion("ans_oper_code like", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeNotLike(String value) {
            addCriterion("ans_oper_code not like", value, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeIn(List<String> values) {
            addCriterion("ans_oper_code in", values, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeNotIn(List<String> values) {
            addCriterion("ans_oper_code not in", values, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeBetween(String value1, String value2) {
            addCriterion("ans_oper_code between", value1, value2, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andAnsOperCodeNotBetween(String value1, String value2) {
            addCriterion("ans_oper_code not between", value1, value2, "ansOperCode");
            return (Criteria) this;
        }

        public Criteria andDeferDateIsNull() {
            addCriterion("defer_date is null");
            return (Criteria) this;
        }

        public Criteria andDeferDateIsNotNull() {
            addCriterion("defer_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeferDateEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date =", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date <>", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateGreaterThan(Date value) {
            addCriterionForJDBCDate("defer_date >", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date >=", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateLessThan(Date value) {
            addCriterionForJDBCDate("defer_date <", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date <=", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateIn(List<Date> values) {
            addCriterionForJDBCDate("defer_date in", values, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("defer_date not in", values, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("defer_date between", value1, value2, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("defer_date not between", value1, value2, "deferDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIsNull() {
            addCriterion("pending_end_date is null");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIsNotNull() {
            addCriterion("pending_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date =", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date <>", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("pending_end_date >", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date >=", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateLessThan(Date value) {
            addCriterionForJDBCDate("pending_end_date <", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date <=", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("pending_end_date in", values, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("pending_end_date not in", values, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pending_end_date between", value1, value2, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pending_end_date not between", value1, value2, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andReturnCountIsNull() {
            addCriterion("return_count is null");
            return (Criteria) this;
        }

        public Criteria andReturnCountIsNotNull() {
            addCriterion("return_count is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCountEqualTo(Integer value) {
            addCriterion("return_count =", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotEqualTo(Integer value) {
            addCriterion("return_count <>", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountGreaterThan(Integer value) {
            addCriterion("return_count >", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("return_count >=", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountLessThan(Integer value) {
            addCriterion("return_count <", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountLessThanOrEqualTo(Integer value) {
            addCriterion("return_count <=", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountIn(List<Integer> values) {
            addCriterion("return_count in", values, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotIn(List<Integer> values) {
            addCriterion("return_count not in", values, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountBetween(Integer value1, Integer value2) {
            addCriterion("return_count between", value1, value2, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotBetween(Integer value1, Integer value2) {
            addCriterion("return_count not between", value1, value2, "returnCount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountIsNull() {
            addCriterion("calc_amount is null");
            return (Criteria) this;
        }

        public Criteria andCalcAmountIsNotNull() {
            addCriterion("calc_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCalcAmountEqualTo(BigDecimal value) {
            addCriterion("calc_amount =", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountNotEqualTo(BigDecimal value) {
            addCriterion("calc_amount <>", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountGreaterThan(BigDecimal value) {
            addCriterion("calc_amount >", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("calc_amount >=", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountLessThan(BigDecimal value) {
            addCriterion("calc_amount <", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("calc_amount <=", value, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountIn(List<BigDecimal> values) {
            addCriterion("calc_amount in", values, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountNotIn(List<BigDecimal> values) {
            addCriterion("calc_amount not in", values, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("calc_amount between", value1, value2, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andCalcAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("calc_amount not between", value1, value2, "calcAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountIsNull() {
            addCriterion("adjust_amount is null");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountIsNotNull() {
            addCriterion("adjust_amount is not null");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountEqualTo(BigDecimal value) {
            addCriterion("adjust_amount =", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountNotEqualTo(BigDecimal value) {
            addCriterion("adjust_amount <>", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountGreaterThan(BigDecimal value) {
            addCriterion("adjust_amount >", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("adjust_amount >=", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountLessThan(BigDecimal value) {
            addCriterion("adjust_amount <", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("adjust_amount <=", value, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountIn(List<BigDecimal> values) {
            addCriterion("adjust_amount in", values, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountNotIn(List<BigDecimal> values) {
            addCriterion("adjust_amount not in", values, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("adjust_amount between", value1, value2, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andAdjustAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("adjust_amount not between", value1, value2, "adjustAmount");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeIsNull() {
            addCriterion("pay_refund_type is null");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeIsNotNull() {
            addCriterion("pay_refund_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeEqualTo(Integer value) {
            addCriterion("pay_refund_type =", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeNotEqualTo(Integer value) {
            addCriterion("pay_refund_type <>", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeGreaterThan(Integer value) {
            addCriterion("pay_refund_type >", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("pay_refund_type >=", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeLessThan(Integer value) {
            addCriterion("pay_refund_type <", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeLessThanOrEqualTo(Integer value) {
            addCriterion("pay_refund_type <=", value, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeIn(List<Integer> values) {
            addCriterion("pay_refund_type in", values, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeNotIn(List<Integer> values) {
            addCriterion("pay_refund_type not in", values, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeBetween(Integer value1, Integer value2) {
            addCriterion("pay_refund_type between", value1, value2, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andPayRefundTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("pay_refund_type not between", value1, value2, "payRefundType");
            return (Criteria) this;
        }

        public Criteria andAskErIdIsNull() {
            addCriterion("ask_er_id is null");
            return (Criteria) this;
        }

        public Criteria andAskErIdIsNotNull() {
            addCriterion("ask_er_id is not null");
            return (Criteria) this;
        }

        public Criteria andAskErIdEqualTo(String value) {
            addCriterion("ask_er_id =", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdNotEqualTo(String value) {
            addCriterion("ask_er_id <>", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdGreaterThan(String value) {
            addCriterion("ask_er_id >", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdGreaterThanOrEqualTo(String value) {
            addCriterion("ask_er_id >=", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdLessThan(String value) {
            addCriterion("ask_er_id <", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdLessThanOrEqualTo(String value) {
            addCriterion("ask_er_id <=", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdLike(String value) {
            addCriterion("ask_er_id like", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdNotLike(String value) {
            addCriterion("ask_er_id not like", value, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdIn(List<String> values) {
            addCriterion("ask_er_id in", values, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdNotIn(List<String> values) {
            addCriterion("ask_er_id not in", values, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdBetween(String value1, String value2) {
            addCriterion("ask_er_id between", value1, value2, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskErIdNotBetween(String value1, String value2) {
            addCriterion("ask_er_id not between", value1, value2, "askErId");
            return (Criteria) this;
        }

        public Criteria andAskCommentIsNull() {
            addCriterion("ask_comment is null");
            return (Criteria) this;
        }

        public Criteria andAskCommentIsNotNull() {
            addCriterion("ask_comment is not null");
            return (Criteria) this;
        }

        public Criteria andAskCommentEqualTo(String value) {
            addCriterion("ask_comment =", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentNotEqualTo(String value) {
            addCriterion("ask_comment <>", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentGreaterThan(String value) {
            addCriterion("ask_comment >", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentGreaterThanOrEqualTo(String value) {
            addCriterion("ask_comment >=", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentLessThan(String value) {
            addCriterion("ask_comment <", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentLessThanOrEqualTo(String value) {
            addCriterion("ask_comment <=", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentLike(String value) {
            addCriterion("ask_comment like", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentNotLike(String value) {
            addCriterion("ask_comment not like", value, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentIn(List<String> values) {
            addCriterion("ask_comment in", values, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentNotIn(List<String> values) {
            addCriterion("ask_comment not in", values, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentBetween(String value1, String value2) {
            addCriterion("ask_comment between", value1, value2, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskCommentNotBetween(String value1, String value2) {
            addCriterion("ask_comment not between", value1, value2, "askComment");
            return (Criteria) this;
        }

        public Criteria andAskTimeIsNull() {
            addCriterion("ask_time is null");
            return (Criteria) this;
        }

        public Criteria andAskTimeIsNotNull() {
            addCriterion("ask_time is not null");
            return (Criteria) this;
        }

        public Criteria andAskTimeEqualTo(Date value) {
            addCriterion("ask_time =", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeNotEqualTo(Date value) {
            addCriterion("ask_time <>", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeGreaterThan(Date value) {
            addCriterion("ask_time >", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ask_time >=", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeLessThan(Date value) {
            addCriterion("ask_time <", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeLessThanOrEqualTo(Date value) {
            addCriterion("ask_time <=", value, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeIn(List<Date> values) {
            addCriterion("ask_time in", values, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeNotIn(List<Date> values) {
            addCriterion("ask_time not in", values, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeBetween(Date value1, Date value2) {
            addCriterion("ask_time between", value1, value2, "askTime");
            return (Criteria) this;
        }

        public Criteria andAskTimeNotBetween(Date value1, Date value2) {
            addCriterion("ask_time not between", value1, value2, "askTime");
            return (Criteria) this;
        }

        public Criteria andAnsErIdIsNull() {
            addCriterion("ans_er_id is null");
            return (Criteria) this;
        }

        public Criteria andAnsErIdIsNotNull() {
            addCriterion("ans_er_id is not null");
            return (Criteria) this;
        }

        public Criteria andAnsErIdEqualTo(String value) {
            addCriterion("ans_er_id =", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdNotEqualTo(String value) {
            addCriterion("ans_er_id <>", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdGreaterThan(String value) {
            addCriterion("ans_er_id >", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdGreaterThanOrEqualTo(String value) {
            addCriterion("ans_er_id >=", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdLessThan(String value) {
            addCriterion("ans_er_id <", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdLessThanOrEqualTo(String value) {
            addCriterion("ans_er_id <=", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdLike(String value) {
            addCriterion("ans_er_id like", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdNotLike(String value) {
            addCriterion("ans_er_id not like", value, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdIn(List<String> values) {
            addCriterion("ans_er_id in", values, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdNotIn(List<String> values) {
            addCriterion("ans_er_id not in", values, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdBetween(String value1, String value2) {
            addCriterion("ans_er_id between", value1, value2, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsErIdNotBetween(String value1, String value2) {
            addCriterion("ans_er_id not between", value1, value2, "ansErId");
            return (Criteria) this;
        }

        public Criteria andAnsCommentIsNull() {
            addCriterion("ans_comment is null");
            return (Criteria) this;
        }

        public Criteria andAnsCommentIsNotNull() {
            addCriterion("ans_comment is not null");
            return (Criteria) this;
        }

        public Criteria andAnsCommentEqualTo(String value) {
            addCriterion("ans_comment =", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentNotEqualTo(String value) {
            addCriterion("ans_comment <>", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentGreaterThan(String value) {
            addCriterion("ans_comment >", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentGreaterThanOrEqualTo(String value) {
            addCriterion("ans_comment >=", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentLessThan(String value) {
            addCriterion("ans_comment <", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentLessThanOrEqualTo(String value) {
            addCriterion("ans_comment <=", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentLike(String value) {
            addCriterion("ans_comment like", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentNotLike(String value) {
            addCriterion("ans_comment not like", value, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentIn(List<String> values) {
            addCriterion("ans_comment in", values, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentNotIn(List<String> values) {
            addCriterion("ans_comment not in", values, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentBetween(String value1, String value2) {
            addCriterion("ans_comment between", value1, value2, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsCommentNotBetween(String value1, String value2) {
            addCriterion("ans_comment not between", value1, value2, "ansComment");
            return (Criteria) this;
        }

        public Criteria andAnsTimeIsNull() {
            addCriterion("ans_time is null");
            return (Criteria) this;
        }

        public Criteria andAnsTimeIsNotNull() {
            addCriterion("ans_time is not null");
            return (Criteria) this;
        }

        public Criteria andAnsTimeEqualTo(Date value) {
            addCriterion("ans_time =", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeNotEqualTo(Date value) {
            addCriterion("ans_time <>", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeGreaterThan(Date value) {
            addCriterion("ans_time >", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ans_time >=", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeLessThan(Date value) {
            addCriterion("ans_time <", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeLessThanOrEqualTo(Date value) {
            addCriterion("ans_time <=", value, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeIn(List<Date> values) {
            addCriterion("ans_time in", values, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeNotIn(List<Date> values) {
            addCriterion("ans_time not in", values, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeBetween(Date value1, Date value2) {
            addCriterion("ans_time between", value1, value2, "ansTime");
            return (Criteria) this;
        }

        public Criteria andAnsTimeNotBetween(Date value1, Date value2) {
            addCriterion("ans_time not between", value1, value2, "ansTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}