package com.cn.zbin.store.dto;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class OrderOperationHistoryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public OrderOperationHistoryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andOrderOperIdIsNull() {
            addCriterion("order_oper_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdIsNotNull() {
            addCriterion("order_oper_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdEqualTo(String value) {
            addCriterion("order_oper_id =", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotEqualTo(String value) {
            addCriterion("order_oper_id <>", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdGreaterThan(String value) {
            addCriterion("order_oper_id >", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_oper_id >=", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLessThan(String value) {
            addCriterion("order_oper_id <", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLessThanOrEqualTo(String value) {
            addCriterion("order_oper_id <=", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdLike(String value) {
            addCriterion("order_oper_id like", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotLike(String value) {
            addCriterion("order_oper_id not like", value, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdIn(List<String> values) {
            addCriterion("order_oper_id in", values, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotIn(List<String> values) {
            addCriterion("order_oper_id not in", values, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdBetween(String value1, String value2) {
            addCriterion("order_oper_id between", value1, value2, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderOperIdNotBetween(String value1, String value2) {
            addCriterion("order_oper_id not between", value1, value2, "orderOperId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("order_id =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("order_id <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("order_id >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_id >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("order_id <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("order_id <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("order_id like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("order_id not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("order_id in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("order_id not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("order_id between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("order_id not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIsNull() {
            addCriterion("order_product_id is null");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIsNotNull() {
            addCriterion("order_product_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdEqualTo(String value) {
            addCriterion("order_product_id =", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotEqualTo(String value) {
            addCriterion("order_product_id <>", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdGreaterThan(String value) {
            addCriterion("order_product_id >", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("order_product_id >=", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLessThan(String value) {
            addCriterion("order_product_id <", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLessThanOrEqualTo(String value) {
            addCriterion("order_product_id <=", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdLike(String value) {
            addCriterion("order_product_id like", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotLike(String value) {
            addCriterion("order_product_id not like", value, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdIn(List<String> values) {
            addCriterion("order_product_id in", values, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotIn(List<String> values) {
            addCriterion("order_product_id not in", values, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdBetween(String value1, String value2) {
            addCriterion("order_product_id between", value1, value2, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOrderProductIdNotBetween(String value1, String value2) {
            addCriterion("order_product_id not between", value1, value2, "orderProductId");
            return (Criteria) this;
        }

        public Criteria andOperateCodeIsNull() {
            addCriterion("operate_code is null");
            return (Criteria) this;
        }

        public Criteria andOperateCodeIsNotNull() {
            addCriterion("operate_code is not null");
            return (Criteria) this;
        }

        public Criteria andOperateCodeEqualTo(String value) {
            addCriterion("operate_code =", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeNotEqualTo(String value) {
            addCriterion("operate_code <>", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeGreaterThan(String value) {
            addCriterion("operate_code >", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeGreaterThanOrEqualTo(String value) {
            addCriterion("operate_code >=", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeLessThan(String value) {
            addCriterion("operate_code <", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeLessThanOrEqualTo(String value) {
            addCriterion("operate_code <=", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeLike(String value) {
            addCriterion("operate_code like", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeNotLike(String value) {
            addCriterion("operate_code not like", value, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeIn(List<String> values) {
            addCriterion("operate_code in", values, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeNotIn(List<String> values) {
            addCriterion("operate_code not in", values, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeBetween(String value1, String value2) {
            addCriterion("operate_code between", value1, value2, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateCodeNotBetween(String value1, String value2) {
            addCriterion("operate_code not between", value1, value2, "operateCode");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNull() {
            addCriterion("operate_type is null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIsNotNull() {
            addCriterion("operate_type is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTypeEqualTo(Integer value) {
            addCriterion("operate_type =", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotEqualTo(Integer value) {
            addCriterion("operate_type <>", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThan(Integer value) {
            addCriterion("operate_type >", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("operate_type >=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThan(Integer value) {
            addCriterion("operate_type <", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeLessThanOrEqualTo(Integer value) {
            addCriterion("operate_type <=", value, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeIn(List<Integer> values) {
            addCriterion("operate_type in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotIn(List<Integer> values) {
            addCriterion("operate_type not in", values, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeBetween(Integer value1, Integer value2) {
            addCriterion("operate_type between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andOperateTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("operate_type not between", value1, value2, "operateType");
            return (Criteria) this;
        }

        public Criteria andDeferDateIsNull() {
            addCriterion("defer_date is null");
            return (Criteria) this;
        }

        public Criteria andDeferDateIsNotNull() {
            addCriterion("defer_date is not null");
            return (Criteria) this;
        }

        public Criteria andDeferDateEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date =", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date <>", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateGreaterThan(Date value) {
            addCriterionForJDBCDate("defer_date >", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date >=", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateLessThan(Date value) {
            addCriterionForJDBCDate("defer_date <", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("defer_date <=", value, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateIn(List<Date> values) {
            addCriterionForJDBCDate("defer_date in", values, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("defer_date not in", values, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("defer_date between", value1, value2, "deferDate");
            return (Criteria) this;
        }

        public Criteria andDeferDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("defer_date not between", value1, value2, "deferDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIsNull() {
            addCriterion("pending_end_date is null");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIsNotNull() {
            addCriterion("pending_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date =", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date <>", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("pending_end_date >", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date >=", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateLessThan(Date value) {
            addCriterionForJDBCDate("pending_end_date <", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("pending_end_date <=", value, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("pending_end_date in", values, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("pending_end_date not in", values, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pending_end_date between", value1, value2, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andPendingEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("pending_end_date not between", value1, value2, "pendingEndDate");
            return (Criteria) this;
        }

        public Criteria andReturnCountIsNull() {
            addCriterion("return_count is null");
            return (Criteria) this;
        }

        public Criteria andReturnCountIsNotNull() {
            addCriterion("return_count is not null");
            return (Criteria) this;
        }

        public Criteria andReturnCountEqualTo(Integer value) {
            addCriterion("return_count =", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotEqualTo(Integer value) {
            addCriterion("return_count <>", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountGreaterThan(Integer value) {
            addCriterion("return_count >", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("return_count >=", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountLessThan(Integer value) {
            addCriterion("return_count <", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountLessThanOrEqualTo(Integer value) {
            addCriterion("return_count <=", value, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountIn(List<Integer> values) {
            addCriterion("return_count in", values, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotIn(List<Integer> values) {
            addCriterion("return_count not in", values, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountBetween(Integer value1, Integer value2) {
            addCriterion("return_count between", value1, value2, "returnCount");
            return (Criteria) this;
        }

        public Criteria andReturnCountNotBetween(Integer value1, Integer value2) {
            addCriterion("return_count not between", value1, value2, "returnCount");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(String value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(String value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(String value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(String value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLike(String value) {
            addCriterion("operator_id like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotLike(String value) {
            addCriterion("operator_id not like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<String> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<String> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(String value1, String value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(String value1, String value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNull() {
            addCriterion("operate_time is null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIsNotNull() {
            addCriterion("operate_time is not null");
            return (Criteria) this;
        }

        public Criteria andOperateTimeEqualTo(Date value) {
            addCriterion("operate_time =", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotEqualTo(Date value) {
            addCriterion("operate_time <>", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThan(Date value) {
            addCriterion("operate_time >", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("operate_time >=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThan(Date value) {
            addCriterion("operate_time <", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
            addCriterion("operate_time <=", value, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeIn(List<Date> values) {
            addCriterion("operate_time in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotIn(List<Date> values) {
            addCriterion("operate_time not in", values, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeBetween(Date value1, Date value2) {
            addCriterion("operate_time between", value1, value2, "operateTime");
            return (Criteria) this;
        }

        public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
            addCriterion("operate_time not between", value1, value2, "operateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table orderoperationhistory
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}