package com.cn.zbin.store.dto;

import java.math.BigDecimal;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProductComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.product_comment_id
     *
     * @mbggenerated
     */
    private String productCommentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.comment_content
     *
     * @mbggenerated
     */
    private String commentContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.comment_level
     *
     * @mbggenerated
     */
    private BigDecimal commentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.img_url
     *
     * @mbggenerated
     */
    private String imgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.comment_reply
     *
     * @mbggenerated
     */
    private String commentReply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productcomment.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.product_comment_id
     *
     * @return the value of productcomment.product_comment_id
     *
     * @mbggenerated
     */
    public String getProductCommentId() {
        return productCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.product_comment_id
     *
     * @param productCommentId the value for productcomment.product_comment_id
     *
     * @mbggenerated
     */
    public void setProductCommentId(String productCommentId) {
        this.productCommentId = productCommentId == null ? null : productCommentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.order_id
     *
     * @return the value of productcomment.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.order_id
     *
     * @param orderId the value for productcomment.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.product_id
     *
     * @return the value of productcomment.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.product_id
     *
     * @param productId the value for productcomment.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.comment_content
     *
     * @return the value of productcomment.comment_content
     *
     * @mbggenerated
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.comment_content
     *
     * @param commentContent the value for productcomment.comment_content
     *
     * @mbggenerated
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.comment_level
     *
     * @return the value of productcomment.comment_level
     *
     * @mbggenerated
     */
    public BigDecimal getCommentLevel() {
        return commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.comment_level
     *
     * @param commentLevel the value for productcomment.comment_level
     *
     * @mbggenerated
     */
    public void setCommentLevel(BigDecimal commentLevel) {
        this.commentLevel = commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.img_url
     *
     * @return the value of productcomment.img_url
     *
     * @mbggenerated
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.img_url
     *
     * @param imgUrl the value for productcomment.img_url
     *
     * @mbggenerated
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.comment_reply
     *
     * @return the value of productcomment.comment_reply
     *
     * @mbggenerated
     */
    public String getCommentReply() {
        return commentReply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.comment_reply
     *
     * @param commentReply the value for productcomment.comment_reply
     *
     * @mbggenerated
     */
    public void setCommentReply(String commentReply) {
        this.commentReply = commentReply == null ? null : commentReply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.create_time
     *
     * @return the value of productcomment.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.create_time
     *
     * @param createTime the value for productcomment.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productcomment.update_time
     *
     * @return the value of productcomment.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productcomment.update_time
     *
     * @param updateTime the value for productcomment.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}