package com.cn.zbin.store.dto;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public ProductInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNull() {
            addCriterion("product_name is null");
            return (Criteria) this;
        }

        public Criteria andProductNameIsNotNull() {
            addCriterion("product_name is not null");
            return (Criteria) this;
        }

        public Criteria andProductNameEqualTo(String value) {
            addCriterion("product_name =", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotEqualTo(String value) {
            addCriterion("product_name <>", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThan(String value) {
            addCriterion("product_name >", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameGreaterThanOrEqualTo(String value) {
            addCriterion("product_name >=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThan(String value) {
            addCriterion("product_name <", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLessThanOrEqualTo(String value) {
            addCriterion("product_name <=", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameLike(String value) {
            addCriterion("product_name like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotLike(String value) {
            addCriterion("product_name not like", value, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameIn(List<String> values) {
            addCriterion("product_name in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotIn(List<String> values) {
            addCriterion("product_name not in", values, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameBetween(String value1, String value2) {
            addCriterion("product_name between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductNameNotBetween(String value1, String value2) {
            addCriterion("product_name not between", value1, value2, "productName");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeIsNull() {
            addCriterion("product_category_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeIsNotNull() {
            addCriterion("product_category_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeEqualTo(String value) {
            addCriterion("product_category_code =", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeNotEqualTo(String value) {
            addCriterion("product_category_code <>", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeGreaterThan(String value) {
            addCriterion("product_category_code >", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_category_code >=", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeLessThan(String value) {
            addCriterion("product_category_code <", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeLessThanOrEqualTo(String value) {
            addCriterion("product_category_code <=", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeLike(String value) {
            addCriterion("product_category_code like", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeNotLike(String value) {
            addCriterion("product_category_code not like", value, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeIn(List<String> values) {
            addCriterion("product_category_code in", values, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeNotIn(List<String> values) {
            addCriterion("product_category_code not in", values, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeBetween(String value1, String value2) {
            addCriterion("product_category_code between", value1, value2, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductCategoryCodeNotBetween(String value1, String value2) {
            addCriterion("product_category_code not between", value1, value2, "productCategoryCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeIsNull() {
            addCriterion("product_brand_code is null");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeIsNotNull() {
            addCriterion("product_brand_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeEqualTo(String value) {
            addCriterion("product_brand_code =", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeNotEqualTo(String value) {
            addCriterion("product_brand_code <>", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeGreaterThan(String value) {
            addCriterion("product_brand_code >", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_brand_code >=", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeLessThan(String value) {
            addCriterion("product_brand_code <", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeLessThanOrEqualTo(String value) {
            addCriterion("product_brand_code <=", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeLike(String value) {
            addCriterion("product_brand_code like", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeNotLike(String value) {
            addCriterion("product_brand_code not like", value, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeIn(List<String> values) {
            addCriterion("product_brand_code in", values, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeNotIn(List<String> values) {
            addCriterion("product_brand_code not in", values, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeBetween(String value1, String value2) {
            addCriterion("product_brand_code between", value1, value2, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductBrandCodeNotBetween(String value1, String value2) {
            addCriterion("product_brand_code not between", value1, value2, "productBrandCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeIsNull() {
            addCriterion("product_type_code is null");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeIsNotNull() {
            addCriterion("product_type_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeEqualTo(String value) {
            addCriterion("product_type_code =", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeNotEqualTo(String value) {
            addCriterion("product_type_code <>", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeGreaterThan(String value) {
            addCriterion("product_type_code >", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_type_code >=", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeLessThan(String value) {
            addCriterion("product_type_code <", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeLessThanOrEqualTo(String value) {
            addCriterion("product_type_code <=", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeLike(String value) {
            addCriterion("product_type_code like", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeNotLike(String value) {
            addCriterion("product_type_code not like", value, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeIn(List<String> values) {
            addCriterion("product_type_code in", values, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeNotIn(List<String> values) {
            addCriterion("product_type_code not in", values, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeBetween(String value1, String value2) {
            addCriterion("product_type_code between", value1, value2, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andProductTypeCodeNotBetween(String value1, String value2) {
            addCriterion("product_type_code not between", value1, value2, "productTypeCode");
            return (Criteria) this;
        }

        public Criteria andStockIsNull() {
            addCriterion("stock is null");
            return (Criteria) this;
        }

        public Criteria andStockIsNotNull() {
            addCriterion("stock is not null");
            return (Criteria) this;
        }

        public Criteria andStockEqualTo(Integer value) {
            addCriterion("stock =", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotEqualTo(Integer value) {
            addCriterion("stock <>", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThan(Integer value) {
            addCriterion("stock >", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockGreaterThanOrEqualTo(Integer value) {
            addCriterion("stock >=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThan(Integer value) {
            addCriterion("stock <", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockLessThanOrEqualTo(Integer value) {
            addCriterion("stock <=", value, "stock");
            return (Criteria) this;
        }

        public Criteria andStockIn(List<Integer> values) {
            addCriterion("stock in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotIn(List<Integer> values) {
            addCriterion("stock not in", values, "stock");
            return (Criteria) this;
        }

        public Criteria andStockBetween(Integer value1, Integer value2) {
            addCriterion("stock between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andStockNotBetween(Integer value1, Integer value2) {
            addCriterion("stock not between", value1, value2, "stock");
            return (Criteria) this;
        }

        public Criteria andCarriageIsNull() {
            addCriterion("carriage is null");
            return (Criteria) this;
        }

        public Criteria andCarriageIsNotNull() {
            addCriterion("carriage is not null");
            return (Criteria) this;
        }

        public Criteria andCarriageEqualTo(BigDecimal value) {
            addCriterion("carriage =", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageNotEqualTo(BigDecimal value) {
            addCriterion("carriage <>", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageGreaterThan(BigDecimal value) {
            addCriterion("carriage >", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("carriage >=", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageLessThan(BigDecimal value) {
            addCriterion("carriage <", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageLessThanOrEqualTo(BigDecimal value) {
            addCriterion("carriage <=", value, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageIn(List<BigDecimal> values) {
            addCriterion("carriage in", values, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageNotIn(List<BigDecimal> values) {
            addCriterion("carriage not in", values, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("carriage between", value1, value2, "carriage");
            return (Criteria) this;
        }

        public Criteria andCarriageNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("carriage not between", value1, value2, "carriage");
            return (Criteria) this;
        }

        public Criteria andServiceIsNull() {
            addCriterion("service is null");
            return (Criteria) this;
        }

        public Criteria andServiceIsNotNull() {
            addCriterion("service is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEqualTo(BigDecimal value) {
            addCriterion("service =", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotEqualTo(BigDecimal value) {
            addCriterion("service <>", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThan(BigDecimal value) {
            addCriterion("service >", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("service >=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThan(BigDecimal value) {
            addCriterion("service <", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("service <=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceIn(List<BigDecimal> values) {
            addCriterion("service in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotIn(List<BigDecimal> values) {
            addCriterion("service not in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("service between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("service not between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andWeightIsNull() {
            addCriterion("weight is null");
            return (Criteria) this;
        }

        public Criteria andWeightIsNotNull() {
            addCriterion("weight is not null");
            return (Criteria) this;
        }

        public Criteria andWeightEqualTo(Integer value) {
            addCriterion("weight =", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotEqualTo(Integer value) {
            addCriterion("weight <>", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThan(Integer value) {
            addCriterion("weight >", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightGreaterThanOrEqualTo(Integer value) {
            addCriterion("weight >=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThan(Integer value) {
            addCriterion("weight <", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightLessThanOrEqualTo(Integer value) {
            addCriterion("weight <=", value, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightIn(List<Integer> values) {
            addCriterion("weight in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotIn(List<Integer> values) {
            addCriterion("weight not in", values, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightBetween(Integer value1, Integer value2) {
            addCriterion("weight between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andWeightNotBetween(Integer value1, Integer value2) {
            addCriterion("weight not between", value1, value2, "weight");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagIsNull() {
            addCriterion("lease_flag is null");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagIsNotNull() {
            addCriterion("lease_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagEqualTo(Boolean value) {
            addCriterion("lease_flag =", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagNotEqualTo(Boolean value) {
            addCriterion("lease_flag <>", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagGreaterThan(Boolean value) {
            addCriterion("lease_flag >", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("lease_flag >=", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagLessThan(Boolean value) {
            addCriterion("lease_flag <", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("lease_flag <=", value, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagIn(List<Boolean> values) {
            addCriterion("lease_flag in", values, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagNotIn(List<Boolean> values) {
            addCriterion("lease_flag not in", values, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("lease_flag between", value1, value2, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("lease_flag not between", value1, value2, "leaseFlag");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysIsNull() {
            addCriterion("lease_min_days is null");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysIsNotNull() {
            addCriterion("lease_min_days is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysEqualTo(Integer value) {
            addCriterion("lease_min_days =", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysNotEqualTo(Integer value) {
            addCriterion("lease_min_days <>", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysGreaterThan(Integer value) {
            addCriterion("lease_min_days >", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("lease_min_days >=", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysLessThan(Integer value) {
            addCriterion("lease_min_days <", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysLessThanOrEqualTo(Integer value) {
            addCriterion("lease_min_days <=", value, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysIn(List<Integer> values) {
            addCriterion("lease_min_days in", values, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysNotIn(List<Integer> values) {
            addCriterion("lease_min_days not in", values, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysBetween(Integer value1, Integer value2) {
            addCriterion("lease_min_days between", value1, value2, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andLeaseMinDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("lease_min_days not between", value1, value2, "leaseMinDays");
            return (Criteria) this;
        }

        public Criteria andBailIsNull() {
            addCriterion("bail is null");
            return (Criteria) this;
        }

        public Criteria andBailIsNotNull() {
            addCriterion("bail is not null");
            return (Criteria) this;
        }

        public Criteria andBailEqualTo(BigDecimal value) {
            addCriterion("bail =", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailNotEqualTo(BigDecimal value) {
            addCriterion("bail <>", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailGreaterThan(BigDecimal value) {
            addCriterion("bail >", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bail >=", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailLessThan(BigDecimal value) {
            addCriterion("bail <", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bail <=", value, "bail");
            return (Criteria) this;
        }

        public Criteria andBailIn(List<BigDecimal> values) {
            addCriterion("bail in", values, "bail");
            return (Criteria) this;
        }

        public Criteria andBailNotIn(List<BigDecimal> values) {
            addCriterion("bail not in", values, "bail");
            return (Criteria) this;
        }

        public Criteria andBailBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bail between", value1, value2, "bail");
            return (Criteria) this;
        }

        public Criteria andBailNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bail not between", value1, value2, "bail");
            return (Criteria) this;
        }

        public Criteria andListingFlagIsNull() {
            addCriterion("listing_flag is null");
            return (Criteria) this;
        }

        public Criteria andListingFlagIsNotNull() {
            addCriterion("listing_flag is not null");
            return (Criteria) this;
        }

        public Criteria andListingFlagEqualTo(Boolean value) {
            addCriterion("listing_flag =", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagNotEqualTo(Boolean value) {
            addCriterion("listing_flag <>", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagGreaterThan(Boolean value) {
            addCriterion("listing_flag >", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("listing_flag >=", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagLessThan(Boolean value) {
            addCriterion("listing_flag <", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("listing_flag <=", value, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagIn(List<Boolean> values) {
            addCriterion("listing_flag in", values, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagNotIn(List<Boolean> values) {
            addCriterion("listing_flag not in", values, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("listing_flag between", value1, value2, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andListingFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("listing_flag not between", value1, value2, "listingFlag");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdIsNull() {
            addCriterion("sale_start_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdIsNotNull() {
            addCriterion("sale_start_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdEqualTo(String value) {
            addCriterion("sale_start_id =", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdNotEqualTo(String value) {
            addCriterion("sale_start_id <>", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdGreaterThan(String value) {
            addCriterion("sale_start_id >", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdGreaterThanOrEqualTo(String value) {
            addCriterion("sale_start_id >=", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdLessThan(String value) {
            addCriterion("sale_start_id <", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdLessThanOrEqualTo(String value) {
            addCriterion("sale_start_id <=", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdLike(String value) {
            addCriterion("sale_start_id like", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdNotLike(String value) {
            addCriterion("sale_start_id not like", value, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdIn(List<String> values) {
            addCriterion("sale_start_id in", values, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdNotIn(List<String> values) {
            addCriterion("sale_start_id not in", values, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdBetween(String value1, String value2) {
            addCriterion("sale_start_id between", value1, value2, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartIdNotBetween(String value1, String value2) {
            addCriterion("sale_start_id not between", value1, value2, "saleStartId");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIsNull() {
            addCriterion("sale_start_time is null");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIsNotNull() {
            addCriterion("sale_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeEqualTo(Date value) {
            addCriterion("sale_start_time =", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotEqualTo(Date value) {
            addCriterion("sale_start_time <>", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeGreaterThan(Date value) {
            addCriterion("sale_start_time >", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sale_start_time >=", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeLessThan(Date value) {
            addCriterion("sale_start_time <", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("sale_start_time <=", value, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeIn(List<Date> values) {
            addCriterion("sale_start_time in", values, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotIn(List<Date> values) {
            addCriterion("sale_start_time not in", values, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeBetween(Date value1, Date value2) {
            addCriterion("sale_start_time between", value1, value2, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("sale_start_time not between", value1, value2, "saleStartTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdIsNull() {
            addCriterion("sale_end_id is null");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdIsNotNull() {
            addCriterion("sale_end_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdEqualTo(String value) {
            addCriterion("sale_end_id =", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdNotEqualTo(String value) {
            addCriterion("sale_end_id <>", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdGreaterThan(String value) {
            addCriterion("sale_end_id >", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdGreaterThanOrEqualTo(String value) {
            addCriterion("sale_end_id >=", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdLessThan(String value) {
            addCriterion("sale_end_id <", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdLessThanOrEqualTo(String value) {
            addCriterion("sale_end_id <=", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdLike(String value) {
            addCriterion("sale_end_id like", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdNotLike(String value) {
            addCriterion("sale_end_id not like", value, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdIn(List<String> values) {
            addCriterion("sale_end_id in", values, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdNotIn(List<String> values) {
            addCriterion("sale_end_id not in", values, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdBetween(String value1, String value2) {
            addCriterion("sale_end_id between", value1, value2, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndIdNotBetween(String value1, String value2) {
            addCriterion("sale_end_id not between", value1, value2, "saleEndId");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIsNull() {
            addCriterion("sale_end_time is null");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIsNotNull() {
            addCriterion("sale_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeEqualTo(Date value) {
            addCriterion("sale_end_time =", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotEqualTo(Date value) {
            addCriterion("sale_end_time <>", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeGreaterThan(Date value) {
            addCriterion("sale_end_time >", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("sale_end_time >=", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeLessThan(Date value) {
            addCriterion("sale_end_time <", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("sale_end_time <=", value, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeIn(List<Date> values) {
            addCriterion("sale_end_time in", values, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotIn(List<Date> values) {
            addCriterion("sale_end_time not in", values, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeBetween(Date value1, Date value2) {
            addCriterion("sale_end_time between", value1, value2, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andSaleEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("sale_end_time not between", value1, value2, "saleEndTime");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlIsNull() {
            addCriterion("introduce_url is null");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlIsNotNull() {
            addCriterion("introduce_url is not null");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlEqualTo(String value) {
            addCriterion("introduce_url =", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlNotEqualTo(String value) {
            addCriterion("introduce_url <>", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlGreaterThan(String value) {
            addCriterion("introduce_url >", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlGreaterThanOrEqualTo(String value) {
            addCriterion("introduce_url >=", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlLessThan(String value) {
            addCriterion("introduce_url <", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlLessThanOrEqualTo(String value) {
            addCriterion("introduce_url <=", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlLike(String value) {
            addCriterion("introduce_url like", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlNotLike(String value) {
            addCriterion("introduce_url not like", value, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlIn(List<String> values) {
            addCriterion("introduce_url in", values, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlNotIn(List<String> values) {
            addCriterion("introduce_url not in", values, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlBetween(String value1, String value2) {
            addCriterion("introduce_url between", value1, value2, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andIntroduceUrlNotBetween(String value1, String value2) {
            addCriterion("introduce_url not between", value1, value2, "introduceUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlIsNull() {
            addCriterion("description_url is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlIsNotNull() {
            addCriterion("description_url is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlEqualTo(String value) {
            addCriterion("description_url =", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlNotEqualTo(String value) {
            addCriterion("description_url <>", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlGreaterThan(String value) {
            addCriterion("description_url >", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlGreaterThanOrEqualTo(String value) {
            addCriterion("description_url >=", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlLessThan(String value) {
            addCriterion("description_url <", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlLessThanOrEqualTo(String value) {
            addCriterion("description_url <=", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlLike(String value) {
            addCriterion("description_url like", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlNotLike(String value) {
            addCriterion("description_url not like", value, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlIn(List<String> values) {
            addCriterion("description_url in", values, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlNotIn(List<String> values) {
            addCriterion("description_url not in", values, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlBetween(String value1, String value2) {
            addCriterion("description_url between", value1, value2, "descriptionUrl");
            return (Criteria) this;
        }

        public Criteria andDescriptionUrlNotBetween(String value1, String value2) {
            addCriterion("description_url not between", value1, value2, "descriptionUrl");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}