package com.cn.zbin.store.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class ProductViewHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.view_id
     *
     * @mbggenerated
     */
    private String viewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.product_id
     *
     * @mbggenerated
     */
    private String productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.is_history
     *
     * @mbggenerated
     */
    private Boolean isHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.view_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date viewTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productviewhistory.view_count
     *
     * @mbggenerated
     */
    private Integer viewCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.view_id
     *
     * @return the value of productviewhistory.view_id
     *
     * @mbggenerated
     */
    public String getViewId() {
        return viewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.view_id
     *
     * @param viewId the value for productviewhistory.view_id
     *
     * @mbggenerated
     */
    public void setViewId(String viewId) {
        this.viewId = viewId == null ? null : viewId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.customer_id
     *
     * @return the value of productviewhistory.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.customer_id
     *
     * @param customerId the value for productviewhistory.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.product_id
     *
     * @return the value of productviewhistory.product_id
     *
     * @mbggenerated
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.product_id
     *
     * @param productId the value for productviewhistory.product_id
     *
     * @mbggenerated
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.is_history
     *
     * @return the value of productviewhistory.is_history
     *
     * @mbggenerated
     */
    public Boolean getIsHistory() {
        return isHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.is_history
     *
     * @param isHistory the value for productviewhistory.is_history
     *
     * @mbggenerated
     */
    public void setIsHistory(Boolean isHistory) {
        this.isHistory = isHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.view_time
     *
     * @return the value of productviewhistory.view_time
     *
     * @mbggenerated
     */
    public Date getViewTime() {
        return viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.view_time
     *
     * @param viewTime the value for productviewhistory.view_time
     *
     * @mbggenerated
     */
    public void setViewTime(Date viewTime) {
        this.viewTime = viewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productviewhistory.view_count
     *
     * @return the value of productviewhistory.view_count
     *
     * @mbggenerated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productviewhistory.view_count
     *
     * @param viewCount the value for productviewhistory.view_count
     *
     * @mbggenerated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }
}