package com.cn.zbin.store.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WeChatMessageHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.message_id
     *
     * @mbggenerated
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.message_content
     *
     * @mbggenerated
     */
    private String messageContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.recv_open_id
     *
     * @mbggenerated
     */
    private String recvOpenId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.send_flag
     *
     * @mbggenerated
     */
    private Boolean sendFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.return_code
     *
     * @mbggenerated
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatmessagehistory.sent_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date sentTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.message_id
     *
     * @return the value of wechatmessagehistory.message_id
     *
     * @mbggenerated
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.message_id
     *
     * @param messageId the value for wechatmessagehistory.message_id
     *
     * @mbggenerated
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId == null ? null : messageId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.message_content
     *
     * @return the value of wechatmessagehistory.message_content
     *
     * @mbggenerated
     */
    public String getMessageContent() {
        return messageContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.message_content
     *
     * @param messageContent the value for wechatmessagehistory.message_content
     *
     * @mbggenerated
     */
    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent == null ? null : messageContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.recv_open_id
     *
     * @return the value of wechatmessagehistory.recv_open_id
     *
     * @mbggenerated
     */
    public String getRecvOpenId() {
        return recvOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.recv_open_id
     *
     * @param recvOpenId the value for wechatmessagehistory.recv_open_id
     *
     * @mbggenerated
     */
    public void setRecvOpenId(String recvOpenId) {
        this.recvOpenId = recvOpenId == null ? null : recvOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.send_flag
     *
     * @return the value of wechatmessagehistory.send_flag
     *
     * @mbggenerated
     */
    public Boolean getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.send_flag
     *
     * @param sendFlag the value for wechatmessagehistory.send_flag
     *
     * @mbggenerated
     */
    public void setSendFlag(Boolean sendFlag) {
        this.sendFlag = sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.return_code
     *
     * @return the value of wechatmessagehistory.return_code
     *
     * @mbggenerated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.return_code
     *
     * @param returnCode the value for wechatmessagehistory.return_code
     *
     * @mbggenerated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.create_time
     *
     * @return the value of wechatmessagehistory.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.create_time
     *
     * @param createTime the value for wechatmessagehistory.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatmessagehistory.sent_time
     *
     * @return the value of wechatmessagehistory.sent_time
     *
     * @mbggenerated
     */
    public Date getSentTime() {
        return sentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatmessagehistory.sent_time
     *
     * @param sentTime the value for wechatmessagehistory.sent_time
     *
     * @mbggenerated
     */
    public void setSentTime(Date sentTime) {
        this.sentTime = sentTime;
    }
}