package com.cn.zbin.store.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WeChatUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.open_id
     *
     * @mbggenerated
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.subscribe_id
     *
     * @mbggenerated
     */
    private String subscribeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.subscribe
     *
     * @mbggenerated
     */
    private Short subscribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.sex
     *
     * @mbggenerated
     */
    private Short sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.head_imgurl
     *
     * @mbggenerated
     */
    private String headImgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.subscribe_time
     *
     * @mbggenerated
     */
    private Long subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.group_id
     *
     * @mbggenerated
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.subscribe_scene
     *
     * @mbggenerated
     */
    private String subscribeScene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.qr_scene
     *
     * @mbggenerated
     */
    private String qrScene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.qr_scene_str
     *
     * @mbggenerated
     */
    private String qrSceneStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatuser.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.open_id
     *
     * @return the value of wechatuser.open_id
     *
     * @mbggenerated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.open_id
     *
     * @param openId the value for wechatuser.open_id
     *
     * @mbggenerated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.subscribe_id
     *
     * @return the value of wechatuser.subscribe_id
     *
     * @mbggenerated
     */
    public String getSubscribeId() {
        return subscribeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.subscribe_id
     *
     * @param subscribeId the value for wechatuser.subscribe_id
     *
     * @mbggenerated
     */
    public void setSubscribeId(String subscribeId) {
        this.subscribeId = subscribeId == null ? null : subscribeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.subscribe
     *
     * @return the value of wechatuser.subscribe
     *
     * @mbggenerated
     */
    public Short getSubscribe() {
        return subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.subscribe
     *
     * @param subscribe the value for wechatuser.subscribe
     *
     * @mbggenerated
     */
    public void setSubscribe(Short subscribe) {
        this.subscribe = subscribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.nick_name
     *
     * @return the value of wechatuser.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.nick_name
     *
     * @param nickName the value for wechatuser.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.sex
     *
     * @return the value of wechatuser.sex
     *
     * @mbggenerated
     */
    public Short getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.sex
     *
     * @param sex the value for wechatuser.sex
     *
     * @mbggenerated
     */
    public void setSex(Short sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.city
     *
     * @return the value of wechatuser.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.city
     *
     * @param city the value for wechatuser.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.country
     *
     * @return the value of wechatuser.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.country
     *
     * @param country the value for wechatuser.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.province
     *
     * @return the value of wechatuser.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.province
     *
     * @param province the value for wechatuser.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.language
     *
     * @return the value of wechatuser.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.language
     *
     * @param language the value for wechatuser.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.head_imgurl
     *
     * @return the value of wechatuser.head_imgurl
     *
     * @mbggenerated
     */
    public String getHeadImgurl() {
        return headImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.head_imgurl
     *
     * @param headImgurl the value for wechatuser.head_imgurl
     *
     * @mbggenerated
     */
    public void setHeadImgurl(String headImgurl) {
        this.headImgurl = headImgurl == null ? null : headImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.subscribe_time
     *
     * @return the value of wechatuser.subscribe_time
     *
     * @mbggenerated
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.subscribe_time
     *
     * @param subscribeTime the value for wechatuser.subscribe_time
     *
     * @mbggenerated
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.union_id
     *
     * @return the value of wechatuser.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.union_id
     *
     * @param unionId the value for wechatuser.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.remark
     *
     * @return the value of wechatuser.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.remark
     *
     * @param remark the value for wechatuser.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.group_id
     *
     * @return the value of wechatuser.group_id
     *
     * @mbggenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.group_id
     *
     * @param groupId the value for wechatuser.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.subscribe_scene
     *
     * @return the value of wechatuser.subscribe_scene
     *
     * @mbggenerated
     */
    public String getSubscribeScene() {
        return subscribeScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.subscribe_scene
     *
     * @param subscribeScene the value for wechatuser.subscribe_scene
     *
     * @mbggenerated
     */
    public void setSubscribeScene(String subscribeScene) {
        this.subscribeScene = subscribeScene == null ? null : subscribeScene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.qr_scene
     *
     * @return the value of wechatuser.qr_scene
     *
     * @mbggenerated
     */
    public String getQrScene() {
        return qrScene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.qr_scene
     *
     * @param qrScene the value for wechatuser.qr_scene
     *
     * @mbggenerated
     */
    public void setQrScene(String qrScene) {
        this.qrScene = qrScene == null ? null : qrScene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.qr_scene_str
     *
     * @return the value of wechatuser.qr_scene_str
     *
     * @mbggenerated
     */
    public String getQrSceneStr() {
        return qrSceneStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.qr_scene_str
     *
     * @param qrSceneStr the value for wechatuser.qr_scene_str
     *
     * @mbggenerated
     */
    public void setQrSceneStr(String qrSceneStr) {
        this.qrSceneStr = qrSceneStr == null ? null : qrSceneStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.create_time
     *
     * @return the value of wechatuser.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.create_time
     *
     * @param createTime the value for wechatuser.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatuser.update_time
     *
     * @return the value of wechatuser.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatuser.update_time
     *
     * @param updateTime the value for wechatuser.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}