package com.cn.zbin.store.dto;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class WxRefundHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.out_refund_no
     *
     * @mbggenerated
     */
    private String outRefundNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.order_oper_id
     *
     * @mbggenerated
     */
    private String orderOperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.transaction_id
     *
     * @mbggenerated
     */
    private String transactionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.out_trade_no
     *
     * @mbggenerated
     */
    private String outTradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.total_fee
     *
     * @mbggenerated
     */
    private Integer totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_fee
     *
     * @mbggenerated
     */
    private Integer refundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.return_code
     *
     * @mbggenerated
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.return_msg
     *
     * @mbggenerated
     */
    private String returnMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.result_code
     *
     * @mbggenerated
     */
    private String resultCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.nonce_str
     *
     * @mbggenerated
     */
    private String nonceStr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.sign
     *
     * @mbggenerated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.err_code
     *
     * @mbggenerated
     */
    private String errCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.err_code_des
     *
     * @mbggenerated
     */
    private String errCodeDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_id
     *
     * @mbggenerated
     */
    private String refundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.cash_fee
     *
     * @mbggenerated
     */
    private Integer cashFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.settlement_refund_fee
     *
     * @mbggenerated
     */
    private Integer settlementRefundFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_count
     *
     * @mbggenerated
     */
    private Integer refundCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_status
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.success_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date successTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_recv_accout
     *
     * @mbggenerated
     */
    private String refundRecvAccout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_account
     *
     * @mbggenerated
     */
    private String refundAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.refund_request_source
     *
     * @mbggenerated
     */
    private String refundRequestSource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.wx_api
     *
     * @mbggenerated
     */
    private String wxApi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.create_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wxrefundhistory.update_time
     *
     * @mbggenerated
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.out_refund_no
     *
     * @return the value of wxrefundhistory.out_refund_no
     *
     * @mbggenerated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.out_refund_no
     *
     * @param outRefundNo the value for wxrefundhistory.out_refund_no
     *
     * @mbggenerated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.order_oper_id
     *
     * @return the value of wxrefundhistory.order_oper_id
     *
     * @mbggenerated
     */
    public String getOrderOperId() {
        return orderOperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.order_oper_id
     *
     * @param orderOperId the value for wxrefundhistory.order_oper_id
     *
     * @mbggenerated
     */
    public void setOrderOperId(String orderOperId) {
        this.orderOperId = orderOperId == null ? null : orderOperId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.order_id
     *
     * @return the value of wxrefundhistory.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.order_id
     *
     * @param orderId the value for wxrefundhistory.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.transaction_id
     *
     * @return the value of wxrefundhistory.transaction_id
     *
     * @mbggenerated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.transaction_id
     *
     * @param transactionId the value for wxrefundhistory.transaction_id
     *
     * @mbggenerated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.out_trade_no
     *
     * @return the value of wxrefundhistory.out_trade_no
     *
     * @mbggenerated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.out_trade_no
     *
     * @param outTradeNo the value for wxrefundhistory.out_trade_no
     *
     * @mbggenerated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.total_fee
     *
     * @return the value of wxrefundhistory.total_fee
     *
     * @mbggenerated
     */
    public Integer getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.total_fee
     *
     * @param totalFee the value for wxrefundhistory.total_fee
     *
     * @mbggenerated
     */
    public void setTotalFee(Integer totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_fee
     *
     * @return the value of wxrefundhistory.refund_fee
     *
     * @mbggenerated
     */
    public Integer getRefundFee() {
        return refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_fee
     *
     * @param refundFee the value for wxrefundhistory.refund_fee
     *
     * @mbggenerated
     */
    public void setRefundFee(Integer refundFee) {
        this.refundFee = refundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.return_code
     *
     * @return the value of wxrefundhistory.return_code
     *
     * @mbggenerated
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.return_code
     *
     * @param returnCode the value for wxrefundhistory.return_code
     *
     * @mbggenerated
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.return_msg
     *
     * @return the value of wxrefundhistory.return_msg
     *
     * @mbggenerated
     */
    public String getReturnMsg() {
        return returnMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.return_msg
     *
     * @param returnMsg the value for wxrefundhistory.return_msg
     *
     * @mbggenerated
     */
    public void setReturnMsg(String returnMsg) {
        this.returnMsg = returnMsg == null ? null : returnMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.result_code
     *
     * @return the value of wxrefundhistory.result_code
     *
     * @mbggenerated
     */
    public String getResultCode() {
        return resultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.result_code
     *
     * @param resultCode the value for wxrefundhistory.result_code
     *
     * @mbggenerated
     */
    public void setResultCode(String resultCode) {
        this.resultCode = resultCode == null ? null : resultCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.nonce_str
     *
     * @return the value of wxrefundhistory.nonce_str
     *
     * @mbggenerated
     */
    public String getNonceStr() {
        return nonceStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.nonce_str
     *
     * @param nonceStr the value for wxrefundhistory.nonce_str
     *
     * @mbggenerated
     */
    public void setNonceStr(String nonceStr) {
        this.nonceStr = nonceStr == null ? null : nonceStr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.sign
     *
     * @return the value of wxrefundhistory.sign
     *
     * @mbggenerated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.sign
     *
     * @param sign the value for wxrefundhistory.sign
     *
     * @mbggenerated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.err_code
     *
     * @return the value of wxrefundhistory.err_code
     *
     * @mbggenerated
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.err_code
     *
     * @param errCode the value for wxrefundhistory.err_code
     *
     * @mbggenerated
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode == null ? null : errCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.err_code_des
     *
     * @return the value of wxrefundhistory.err_code_des
     *
     * @mbggenerated
     */
    public String getErrCodeDes() {
        return errCodeDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.err_code_des
     *
     * @param errCodeDes the value for wxrefundhistory.err_code_des
     *
     * @mbggenerated
     */
    public void setErrCodeDes(String errCodeDes) {
        this.errCodeDes = errCodeDes == null ? null : errCodeDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_id
     *
     * @return the value of wxrefundhistory.refund_id
     *
     * @mbggenerated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_id
     *
     * @param refundId the value for wxrefundhistory.refund_id
     *
     * @mbggenerated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.cash_fee
     *
     * @return the value of wxrefundhistory.cash_fee
     *
     * @mbggenerated
     */
    public Integer getCashFee() {
        return cashFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.cash_fee
     *
     * @param cashFee the value for wxrefundhistory.cash_fee
     *
     * @mbggenerated
     */
    public void setCashFee(Integer cashFee) {
        this.cashFee = cashFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.settlement_refund_fee
     *
     * @return the value of wxrefundhistory.settlement_refund_fee
     *
     * @mbggenerated
     */
    public Integer getSettlementRefundFee() {
        return settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.settlement_refund_fee
     *
     * @param settlementRefundFee the value for wxrefundhistory.settlement_refund_fee
     *
     * @mbggenerated
     */
    public void setSettlementRefundFee(Integer settlementRefundFee) {
        this.settlementRefundFee = settlementRefundFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_count
     *
     * @return the value of wxrefundhistory.refund_count
     *
     * @mbggenerated
     */
    public Integer getRefundCount() {
        return refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_count
     *
     * @param refundCount the value for wxrefundhistory.refund_count
     *
     * @mbggenerated
     */
    public void setRefundCount(Integer refundCount) {
        this.refundCount = refundCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_status
     *
     * @return the value of wxrefundhistory.refund_status
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_status
     *
     * @param refundStatus the value for wxrefundhistory.refund_status
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.success_time
     *
     * @return the value of wxrefundhistory.success_time
     *
     * @mbggenerated
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.success_time
     *
     * @param successTime the value for wxrefundhistory.success_time
     *
     * @mbggenerated
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_recv_accout
     *
     * @return the value of wxrefundhistory.refund_recv_accout
     *
     * @mbggenerated
     */
    public String getRefundRecvAccout() {
        return refundRecvAccout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_recv_accout
     *
     * @param refundRecvAccout the value for wxrefundhistory.refund_recv_accout
     *
     * @mbggenerated
     */
    public void setRefundRecvAccout(String refundRecvAccout) {
        this.refundRecvAccout = refundRecvAccout == null ? null : refundRecvAccout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_account
     *
     * @return the value of wxrefundhistory.refund_account
     *
     * @mbggenerated
     */
    public String getRefundAccount() {
        return refundAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_account
     *
     * @param refundAccount the value for wxrefundhistory.refund_account
     *
     * @mbggenerated
     */
    public void setRefundAccount(String refundAccount) {
        this.refundAccount = refundAccount == null ? null : refundAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.refund_request_source
     *
     * @return the value of wxrefundhistory.refund_request_source
     *
     * @mbggenerated
     */
    public String getRefundRequestSource() {
        return refundRequestSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.refund_request_source
     *
     * @param refundRequestSource the value for wxrefundhistory.refund_request_source
     *
     * @mbggenerated
     */
    public void setRefundRequestSource(String refundRequestSource) {
        this.refundRequestSource = refundRequestSource == null ? null : refundRequestSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.wx_api
     *
     * @return the value of wxrefundhistory.wx_api
     *
     * @mbggenerated
     */
    public String getWxApi() {
        return wxApi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.wx_api
     *
     * @param wxApi the value for wxrefundhistory.wx_api
     *
     * @mbggenerated
     */
    public void setWxApi(String wxApi) {
        this.wxApi = wxApi == null ? null : wxApi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.create_time
     *
     * @return the value of wxrefundhistory.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.create_time
     *
     * @param createTime the value for wxrefundhistory.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wxrefundhistory.update_time
     *
     * @return the value of wxrefundhistory.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wxrefundhistory.update_time
     *
     * @param updateTime the value for wxrefundhistory.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}