package com.cn.zbin.management.mapper;

import com.cn.zbin.management.dto.CustomerDiseaseHistory;
import com.cn.zbin.management.dto.CustomerDiseaseHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerDiseaseHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int countByExample(CustomerDiseaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerDiseaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int insert(CustomerDiseaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int insertSelective(CustomerDiseaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    List<CustomerDiseaseHistory> selectByExample(CustomerDiseaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    CustomerDiseaseHistory selectByPrimaryKey(String historyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CustomerDiseaseHistory record, @Param("example") CustomerDiseaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CustomerDiseaseHistory record, @Param("example") CustomerDiseaseHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CustomerDiseaseHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customerdiseasehistory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CustomerDiseaseHistory record);
}